/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/planning`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/post/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/projects/[projectId]`, params: Router.UnknownInputParams & { projectId: string | number; } } | { pathname: `/work-items/[workItemId]`, params: Router.UnknownInputParams & { workItemId: string | number; } } | { pathname: `/work-items/[workItemId]/workspace`, params: Router.UnknownInputParams & { workItemId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/planning`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/post/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/projects/[projectId]`, params: Router.UnknownOutputParams & { projectId: string; } } | { pathname: `/work-items/[workItemId]`, params: Router.UnknownOutputParams & { workItemId: string; } } | { pathname: `/work-items/[workItemId]/workspace`, params: Router.UnknownOutputParams & { workItemId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `/planning${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/planning`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/post/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/projects/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/work-items/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/work-items/${Router.SingleRoutePart<T>}/workspace${`?${string}` | `#${string}` | ''}` | { pathname: `/post/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/projects/[projectId]`, params: Router.UnknownInputParams & { projectId: string | number; } } | { pathname: `/work-items/[workItemId]`, params: Router.UnknownInputParams & { workItemId: string | number; } } | { pathname: `/work-items/[workItemId]/workspace`, params: Router.UnknownInputParams & { workItemId: string | number; } };
    }
  }
}
