/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/chat`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `/planning`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/projects`; params?: Router.UnknownInputParams; } | { pathname: `/tasks/outcomes`; params?: Router.UnknownInputParams; } | { pathname: `/tasks/queue`; params?: Router.UnknownInputParams; } | { pathname: `/post/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/projects/[projectId]`, params: Router.UnknownInputParams & { projectId: string | number; } } | { pathname: `/work-items/[workItemId]`, params: Router.UnknownInputParams & { workItemId: string | number; } } | { pathname: `/work-items/[workItemId]/workspace`, params: Router.UnknownInputParams & { workItemId: string | number; } } | { pathname: `/providers/[provider]`, params: Router.UnknownInputParams & { provider: string | number; } } | { pathname: `/planning/sessions/[sessionId]`, params: Router.UnknownInputParams & { sessionId: string | number; } } | { pathname: `/sessions/[sessionId]`, params: Router.UnknownInputParams & { sessionId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/tasks`; params?: Router.UnknownOutputParams; } | { pathname: `/planning`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/projects`; params?: Router.UnknownOutputParams; } | { pathname: `/tasks/outcomes`; params?: Router.UnknownOutputParams; } | { pathname: `/tasks/queue`; params?: Router.UnknownOutputParams; } | { pathname: `/post/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/projects/[projectId]`, params: Router.UnknownOutputParams & { projectId: string; } } | { pathname: `/work-items/[workItemId]`, params: Router.UnknownOutputParams & { workItemId: string; } } | { pathname: `/work-items/[workItemId]/workspace`, params: Router.UnknownOutputParams & { workItemId: string; } } | { pathname: `/providers/[provider]`, params: Router.UnknownOutputParams & { provider: string; } } | { pathname: `/planning/sessions/[sessionId]`, params: Router.UnknownOutputParams & { sessionId: string; } } | { pathname: `/sessions/[sessionId]`, params: Router.UnknownOutputParams & { sessionId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/chat${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/tasks${`?${string}` | `#${string}` | ''}` | `/planning${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/projects${`?${string}` | `#${string}` | ''}` | `/tasks/outcomes${`?${string}` | `#${string}` | ''}` | `/tasks/queue${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/chat`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `/planning`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/projects`; params?: Router.UnknownInputParams; } | { pathname: `/tasks/outcomes`; params?: Router.UnknownInputParams; } | { pathname: `/tasks/queue`; params?: Router.UnknownInputParams; } | `/post/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/projects/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/work-items/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/work-items/${Router.SingleRoutePart<T>}/workspace${`?${string}` | `#${string}` | ''}` | `/providers/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/planning/sessions/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/sessions/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/post/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/projects/[projectId]`, params: Router.UnknownInputParams & { projectId: string | number; } } | { pathname: `/work-items/[workItemId]`, params: Router.UnknownInputParams & { workItemId: string | number; } } | { pathname: `/work-items/[workItemId]/workspace`, params: Router.UnknownInputParams & { workItemId: string | number; } } | { pathname: `/providers/[provider]`, params: Router.UnknownInputParams & { provider: string | number; } } | { pathname: `/planning/sessions/[sessionId]`, params: Router.UnknownInputParams & { sessionId: string | number; } } | { pathname: `/sessions/[sessionId]`, params: Router.UnknownInputParams & { sessionId: string | number; } };
    }
  }
}
