/// <reference types="@cloudflare/workers-types" />
/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import * as Sentry from "@sentry/cloudflare";
import {
  handleImageOptimization,
  DEFAULT_DEVICE_SIZES,
  DEFAULT_IMAGE_SIZES,
} from "vinext/server/image-optimization";
import type { ImageConfig } from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";
import { runWithDb } from "../src/lib/db-client-lazy";
import { wrapFetch } from "./lib/otel";
import {
  applyRuntimeAuthEnv,
  getHyperdriveConnectionString,
  getSentryOptions,
} from "./runtime-env";

interface Env {
  ASSETS: Fetcher;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: {
          format: string;
          quality: number;
        }): Promise<{ response(): Response }>;
      };
    };
  };
  HYPERDRIVE: { connectionString: string };
  GATEWAY_URL?: string;
  NUDGE_SHARED_SECRET?: string;
  [key: string]: unknown;
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

// Image security config. SVG sources with .svg extension auto-skip the
// optimization endpoint on the client side (served directly, no proxy).
// To route SVGs through the optimizer (with security headers), set
// dangerouslyAllowSVG: true in next.config.js and uncomment below:
// const imageConfig: ImageConfig = { dangerouslyAllowSVG: true };

export default Sentry.withSentry(
  (env: Record<string, unknown> | undefined) => getSentryOptions(env),
  {
    // Autonomous backlog driver — runs on the Cron trigger in wrangler.jsonc.
    // Dispatches ready work items up to the concurrency cap + a daily rate
    // limit, rotating across agents. Gated on BOB_AUTO_DRAIN_ENABLED so it can
    // be turned off with a var change, no redeploy.
    scheduled: async (
      _event: unknown,
      rawEnv: Record<string, unknown> | undefined,
      ctx: ExecutionContext,
    ): Promise<void> => {
      const runtimeEnv = (rawEnv ?? {}) as Env;
      const autoDrainOn =
        String(runtimeEnv.BOB_AUTO_DRAIN_ENABLED ?? "") === "true";
      const autoMergeOn =
        String(runtimeEnv.BOB_AUTO_MERGE_ENABLED ?? "") === "true" &&
        !!runtimeEnv.ANTHROPIC_API_KEY;
      if (!autoDrainOn && !autoMergeOn) {
        return;
      }
      const concurrency = Number(runtimeEnv.BOB_AUTO_DRAIN_CONCURRENCY ?? 4);
      const dailyCap = Number(runtimeEnv.BOB_AUTO_DRAIN_DAILY_CAP ?? 20);
      const nudgeSecret =
        runtimeEnv.NUDGE_SHARED_SECRET ?? process.env.NUDGE_SHARED_SECRET;
      if (nudgeSecret) {
        (globalThis as any).NUDGE_SHARED_SECRET = nudgeSecret;
      }
      const { connectionString, isHyperdrive } =
        getHyperdriveConnectionString(runtimeEnv);
      const work = runWithDb(connectionString, isHyperdrive, async () => {
        // 1. Dispatch backlog work.
        if (autoDrainOn) {
          const { autoDrainBacklog } = await import(
            "@bob/api/handlers/autoDrain"
          );
          const result = await autoDrainBacklog({ concurrency, dailyCap });
          console.log(
            `[auto-drain] dispatched=${result.dispatched} running=${result.running} today=${result.dispatchedToday}` +
              (result.reason ? ` reason="${result.reason}"` : "") +
              (result.items.length
                ? ` items=${result.items.map((i) => `${i.identifier}:${i.agentType}`).join(",")}`
                : ""),
          );
        }
        // 2. Review + auto-merge the PRs those tasks produced.
        if (autoMergeOn) {
          const { autoReviewAndMerge } = await import(
            "@bob/api/handlers/autoMergeReview"
          );
          const r = await autoReviewAndMerge({
            maxPerRun: Number(runtimeEnv.BOB_AUTO_MERGE_MAX_PER_RUN ?? 5),
            reviewModel:
              (runtimeEnv.BOB_AUTO_MERGE_MODEL as string | undefined) ??
              "claude-sonnet-5",
            anthropicApiKey: runtimeEnv.ANTHROPIC_API_KEY as string,
            dryRun: String(runtimeEnv.BOB_AUTO_MERGE_DRY_RUN ?? "") === "true",
            forgejoToken: runtimeEnv.BOB_FORGEJO_TOKEN as string | undefined,
            forgejoInstanceUrl:
              (runtimeEnv.BOB_FORGEJO_INSTANCE_URL as string | undefined) ??
              "https://git.forgegraf.com",
          });
          console.log(
            `[auto-merge] scanned=${r.scanned} reviewed=${r.reviewed} merged=${r.merged} skipped=${r.skipped}` +
              (r.items.length
                ? ` items=${r.items.map((i) => `${i.pr}:${i.action}${i.reason ? `(${i.reason})` : ""}`).join(", ")}`
                : ""),
          );
        }
      });
      ctx.waitUntil(work);
      await work;
    },
    fetch: wrapFetch(
      async (
        request: Request,
        rawEnv: Record<string, unknown> | undefined,
        ctx,
      ): Promise<Response> => {
        const url = new URL(request.url);
        const runtimeEnv = (rawEnv ?? {}) as Env;
        applyRuntimeAuthEnv(runtimeEnv);

        // WebSocket proxy to gateway — forward upgrade to origin
        if (
          url.pathname === "/ws/sessions" &&
          request.headers.get("Upgrade") === "websocket"
        ) {
          const gatewayOrigin =
            runtimeEnv.GATEWAY_URL ||
            process.env.GATEWAY_URL ||
            "https://ws.blder.bot";
          const target = `${gatewayOrigin}/sessions${url.search}`;
          return fetch(target, request);
        }

        // Image optimization via Cloudflare Images binding.
        if (url.pathname === "/_vinext/image") {
          if (!runtimeEnv.ASSETS || !runtimeEnv.IMAGES) {
            return new Response(
              "Image optimization is unavailable in this runtime",
              { status: 503 },
            );
          }
          const allowedWidths = [
            ...DEFAULT_DEVICE_SIZES,
            ...DEFAULT_IMAGE_SIZES,
          ];
          return handleImageOptimization(
            request,
            {
              fetchAsset: (path) =>
                runtimeEnv.ASSETS.fetch(
                  new Request(new URL(path, request.url)),
                ),
              transformImage: async (body, { width, format, quality }) => {
                const result = await runtimeEnv.IMAGES.input(body)
                  .transform(width > 0 ? { width } : {})
                  .output({ format, quality });
                return result.response();
              },
            },
            allowedWidths,
          );
        }

        // Expose secrets to server-side code via globalThis.
        const nudgeSecret =
          runtimeEnv.NUDGE_SHARED_SECRET ?? process.env.NUDGE_SHARED_SECRET;
        if (nudgeSecret) {
          (globalThis as any).NUDGE_SHARED_SECRET = nudgeSecret;
        }

        // Run vinext with a request-scoped DB client.
        const { connectionString, isHyperdrive } =
          getHyperdriveConnectionString(runtimeEnv);
        return runWithDb(connectionString, isHyperdrive, () =>
          handler.fetch(request, runtimeEnv, ctx),
        );
      },
    ),
  },
);
