/// <reference types="@cloudflare/workers-types" />
/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import { handleImageOptimization, DEFAULT_DEVICE_SIZES, DEFAULT_IMAGE_SIZES } from "vinext/server/image-optimization";
import type { ImageConfig } from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";
import { runWithDb } from "../src/lib/db-client-lazy";

interface Env {
  ASSETS: Fetcher;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
  HYPERDRIVE: { connectionString: string };
  GATEWAY_URL?: string;
  NUDGE_SHARED_SECRET?: string;
  [key: string]: unknown;
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

// Image security config. SVG sources with .svg extension auto-skip the
// optimization endpoint on the client side (served directly, no proxy).
// To route SVGs through the optimizer (with security headers), set
// dangerouslyAllowSVG: true in next.config.js and uncomment below:
// const imageConfig: ImageConfig = { dangerouslyAllowSVG: true };

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    // WebSocket proxy to gateway — forward upgrade to origin
    if (url.pathname === "/ws/sessions" && request.headers.get("Upgrade") === "websocket") {
      const gatewayOrigin = env.GATEWAY_URL || "https://ws.blder.bot";
      const target = `${gatewayOrigin}/sessions${url.search}`;
      return fetch(target, request);
    }

    // Image optimization via Cloudflare Images binding.
    // The parseImageParams validation inside handleImageOptimization
    // normalizes backslashes and validates the origin hasn't changed.
    if (url.pathname === "/_vinext/image") {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
      return handleImageOptimization(request, {
        fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
        transformImage: async (body, { width, format, quality }) => {
          const result = await env.IMAGES.input(body).transform(width > 0 ? { width } : {}).output({ format, quality });
          return result.response();
        },
      }, allowedWidths);
    }

    // Expose secrets to server-side code via globalThis.
    if (env.NUDGE_SHARED_SECRET) {
      (globalThis as any).NUDGE_SHARED_SECRET = env.NUDGE_SHARED_SECRET;
    }

    // Run vinext with a request-scoped DB client. This ensures all queries
    // within this request share one postgres connection (avoids exhausting
    // Hyperdrive's per-request TCP limit and cross-request I/O errors).
    const dbUrl = env.HYPERDRIVE.connectionString;
    return runWithDb(dbUrl, true, () => handler.fetch(request, env, ctx));
  },
};
