/// <reference types="@cloudflare/workers-types" />
/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import * as Sentry from "@sentry/cloudflare";
import {
  handleImageOptimization,
  DEFAULT_DEVICE_SIZES,
  DEFAULT_IMAGE_SIZES,
} from "vinext/server/image-optimization";
import type { ImageConfig } from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";
import { runWithDb } from "../src/lib/db-client-lazy";
import {
  isAllowedHermesServiceRequest,
  verifyOriginAuthorization,
} from "../src/lib/hermes-notifications";
import {
  createHermesBootstrapRequest,
  createHermesNativeApiRequest,
  createHermesProxyRequest,
  extractHermesSessionToken,
  fetchHermesOverview,
  getHermesLoginRedirect,
  isAuthorizedHermesOperator,
  isAllowedHermesProxyServiceRequest,
  isHermesNativeApiPath,
  isHermesProxyPath,
  sanitizeHermesResponse,
  validateHermesBrowserRequest,
  validateHermesNativeApiMutation,
} from "../src/lib/hermes-proxy";
import { wrapFetch } from "./lib/otel";
import {
  applyRuntimeAuthEnv,
  applyRuntimeServiceEnv,
  getHyperdriveConnectionString,
  getSentryOptions,
} from "./runtime-env";

interface Env {
  ASSETS: Fetcher;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: {
          format: string;
          quality: number;
        }): Promise<{ response(): Response }>;
      };
    };
  };
  HYPERDRIVE: { connectionString: string };
  GATEWAY_URL?: string;
  NUDGE_SHARED_SECRET?: string;
  SKILLFLEET_NOTIFICATION_SECRET?: string;
  HERMES_ORIGIN_TOKEN?: string;
  HERMES_PROXY_ORIGIN_TOKEN?: string;
  HERMES_ORIGIN_URL?: string;
  HERMES_OPERATOR_USER_IDS?: string;
  [key: string]: unknown;
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

// Image security config. SVG sources with .svg extension auto-skip the
// optimization endpoint on the client side (served directly, no proxy).
// To route SVGs through the optimizer (with security headers), set
// dangerouslyAllowSVG: true in next.config.js and uncomment below:
// const imageConfig: ImageConfig = { dangerouslyAllowSVG: true };

export default Sentry.withSentry(
  (env: Record<string, unknown> | undefined) => getSentryOptions(env),
  {
    // Autonomous backlog driver — runs on the Cron trigger in wrangler.jsonc.
    // Dispatches ready work items up to the concurrency cap + a daily rate
    // limit, rotating across agents. Gated on BOB_AUTO_DRAIN_ENABLED so it can
    // be turned off with a var change, no redeploy.
    scheduled: async (
      _event: unknown,
      rawEnv: Record<string, unknown> | undefined,
      ctx: ExecutionContext,
    ): Promise<void> => {
      const runtimeEnv = (rawEnv ?? {}) as Env;
      const autoDrainOn =
        String(runtimeEnv.BOB_AUTO_DRAIN_ENABLED ?? "") === "true";
      // Review is done by a runner agent (dispatchReviewSession), not a model
      // API — so this no longer requires ANTHROPIC_API_KEY.
      const autoMergeOn =
        String(runtimeEnv.BOB_AUTO_MERGE_ENABLED ?? "") === "true";
      // Checklist-driven execution driver. Dark by default (off): flip
      // BOB_ADVANCE_CHECKLIST_ENABLED=true to roll it out, same lever as the
      // other drivers — no redeploy needed to disable.
      const advanceChecklistOn =
        String(runtimeEnv.BOB_ADVANCE_CHECKLIST_ENABLED ?? "") === "true";
      // Deploy-stage tracker: reads Forgejo Actions + ForgeGraph deployment
      // evidence for each merge and writes it back to the card/work item.
      const deployTrackingOn =
        String(runtimeEnv.BOB_DEPLOY_TRACKING_ENABLED ?? "") === "true";
      // Keep the Linear backlog fresh server-side (default on) — the sync was
      // webhook-only, so new Linear tasks stopped reaching Bob when the webhook
      // went quiet. This pull backfills + maintains. Gated to ~every 15 min to
      // stay well under Linear's API rate limit.
      const syncLinearOn =
        String((runtimeEnv as any).BOB_AUTO_SYNC_LINEAR_ENABLED ?? "true") !== "false";
      const scheduledTime =
        typeof (_event as any)?.scheduledTime === "number"
          ? (_event as any).scheduledTime
          : Date.now();
      const syncLinearDue = Math.floor(scheduledTime / 60_000) % 15 === 0;
      if (!autoDrainOn && !autoMergeOn && !syncLinearOn && !advanceChecklistOn && !deployTrackingOn) {
        return;
      }
      const concurrency = Number(runtimeEnv.BOB_AUTO_DRAIN_CONCURRENCY ?? 4);
      const dailyCap = Number(runtimeEnv.BOB_AUTO_DRAIN_DAILY_CAP ?? 20);
      const nudgeSecret =
        runtimeEnv.NUDGE_SHARED_SECRET ?? process.env.NUDGE_SHARED_SECRET;
      if (nudgeSecret) {
        (globalThis as any).NUDGE_SHARED_SECRET = nudgeSecret;
      }
      const { connectionString, isHyperdrive } =
        getHyperdriveConnectionString(runtimeEnv);
      const work = runWithDb(connectionString, isHyperdrive, async () => {
        // 0. Keep the Linear backlog in sync (backfill + ongoing). Runs
        // server-side with full DB access — no user session needed, which is
        // why the cron is the right home for this (the RPC requires a browser
        // session). Imports open Linear issues as work items; a Linear "Todo"
        // maps to Bob "todo", which auto-drain then dispatches.
        if (syncLinearOn && syncLinearDue) {
          try {
            const { db } = await import("@bob/db/client");
            const { syncLinearProjects } = await import(
              "@bob/api/handlers/linearSetup"
            );
            const { workspaceIntegrations, workspaceMembers } = await import(
              "@bob/db/schema"
            );
            const { eq, and, asc } = await import("@bob/db");
            const integrations = await db.query.workspaceIntegrations.findMany({
              where: and(
                eq(workspaceIntegrations.provider, "linear"),
                eq(workspaceIntegrations.enabled, true),
              ),
            });
            for (const integ of integrations) {
              const owner = await db.query.workspaceMembers.findFirst({
                where: eq(workspaceMembers.workspaceId, integ.workspaceId),
                columns: { userId: true },
                orderBy: [asc(workspaceMembers.joinedAt)],
              });
              if (!owner) continue;
              const r = await syncLinearProjects(
                { db, userId: owner.userId },
                { workspaceId: integ.workspaceId, importIssues: true },
              );
              console.log(
                `[linear-sync] ws=${integ.workspaceId} projectsCreated=${r.projectsCreated} projectsExisting=${r.projectsExisting} issuesImported=${r.issuesImported} issuesUpdated=${r.issuesUpdated}` +
                  (r.issuesTruncated ? " (issues truncated)" : ""),
              );
            }
          } catch (err) {
            console.error("[linear-sync] failed:", err);
            // Persist the failure where the Settings UI can show it. Leave
            // lastSyncedAt alone — its age is what the staleness alert below
            // measures.
            try {
              const { db } = await import("@bob/db/client");
              const { workspaceIntegrations } = await import("@bob/db/schema");
              const { eq } = await import("@bob/db");
              const msg = err instanceof Error ? err.message : String(err);
              await db
                .update(workspaceIntegrations)
                .set({ lastSyncResult: `error: ${msg}`.slice(0, 500) })
                .where(eq(workspaceIntegrations.provider, "linear"));
            } catch {
              /* best-effort */
            }
          }
        }
        // 0b. Staleness guard: the sync above fails silently from the queue's
        // point of view (the cron keeps ticking, counters look fine), so
        // escalate when no sync has completed for over an hour. Kanbanger's
        // API broke on 2026-08-14 and nothing noticed for 6 days.
        if (syncLinearOn) {
          try {
            const { db } = await import("@bob/db/client");
            const { workspaceIntegrations } = await import("@bob/db/schema");
            const { eq, and } = await import("@bob/db");
            const staleMs = Number(
              runtimeEnv.BOB_LINEAR_SYNC_STALE_MS ?? 60 * 60 * 1000,
            );
            const rows = await db.query.workspaceIntegrations.findMany({
              where: and(
                eq(workspaceIntegrations.provider, "linear"),
                eq(workspaceIntegrations.enabled, true),
              ),
              columns: { workspaceId: true, lastSyncedAt: true, lastSyncResult: true },
            });
            const now = Date.now();
            const stale = rows.filter(
              (r) =>
                r.lastSyncedAt &&
                now - new Date(r.lastSyncedAt).getTime() > staleMs,
            );
            if (stale.length) {
              const { buildFailurePayload, getFailureSentryTags } =
                await import("@bob/observability/failures");
              const failure = {
                surface: "job" as const,
                operation: "linear_sync",
                error: new Error(
                  `tracker sync stale for ${stale.length} integration(s): ` +
                    stale
                      .map(
                        (r) =>
                          `ws=${r.workspaceId} lastSyncedAt=${r.lastSyncedAt} last=${r.lastSyncResult ?? "-"}`,
                      )
                      .join("; "),
                ),
                alertId: "linear-sync-stale",
                tenant: runtimeEnv.BOB_TENANT_ID
                  ? { tenantId: String(runtimeEnv.BOB_TENANT_ID) }
                  : undefined,
              };
              console.error(
                "[linear-sync] STALE — queue is not being fed",
                buildFailurePayload(failure),
              );
              Sentry.withScope((scope) => {
                scope.setLevel("error");
                scope.setTags(getFailureSentryTags(failure));
                scope.setContext("failure", buildFailurePayload(failure));
                Sentry.captureException(failure.error);
              });
            }
          } catch (err) {
            console.error("[linear-sync] staleness check failed:", err);
          }
        }
        // 1. Dispatch backlog work.
        if (autoDrainOn) {
          // 1a. Reap zombie sessions FIRST so freed slots are usable this tick.
          // A session whose runner died lingers in an active status forever and
          // permanently consumes an autoDrain slot; enough of them starve the
          // whole pipeline ("no free slots"). Gated so it can be disabled with a
          // var change, no redeploy. Best-effort — a reaper failure must not
          // block dispatch, so it's caught and logged, never thrown.
          if (String(runtimeEnv.BOB_SESSION_REAP_ENABLED ?? "true") !== "false") {
            try {
              const { reapStuckSessions } = await import(
                "@bob/api/handlers/reapStuckSessions"
              );
              const reap = await reapStuckSessions({
                leaseGraceMs: runtimeEnv.BOB_SESSION_REAP_LEASE_GRACE_MS
                  ? Number(runtimeEnv.BOB_SESSION_REAP_LEASE_GRACE_MS)
                  : undefined,
                hardTimeoutMs: runtimeEnv.BOB_SESSION_REAP_HARD_TIMEOUT_MS
                  ? Number(runtimeEnv.BOB_SESSION_REAP_HARD_TIMEOUT_MS)
                  : undefined,
              });
              if (reap.reaped > 0) {
                console.log(
                  `[session-reap] reaped=${reap.reaped} sessions=${reap.sessions
                    .map((s) => `${s.id.slice(0, 8)}:${s.status}`)
                    .join(",")}`,
                );
              }
              // Early-warning: steady-state reaps 0. A spike (many sessions dead
              // at once) means a runner crashed/restarted or is dispatching-but-
              // never-claiming (the 2026-07-29 outage cleared 16 at once). Alert
              // so an unhealthy runner surfaces before the backlog visibly
              // starves. Observability only — never affects dispatch.
              const reapAlertThreshold = Number(
                runtimeEnv.BOB_SESSION_REAP_ALERT_THRESHOLD ?? 5,
              );
              if (reap.reaped >= reapAlertThreshold) {
                const { buildFailurePayload, getFailureSentryTags } =
                  await import("@bob/observability/failures");
                const failure = {
                  surface: "job" as const,
                  operation: "reap_stuck_sessions",
                  error: new Error(
                    `stuck-session reaper cleared ${reap.reaped} sessions in one tick (>= ${reapAlertThreshold}) — a runner is likely unhealthy (crashed/restarted or claiming no work)`,
                  ),
                  alertId: "session-reap-spike",
                  tenant: runtimeEnv.BOB_TENANT_ID
                    ? { tenantId: String(runtimeEnv.BOB_TENANT_ID) }
                    : undefined,
                };
                console.error(
                  "[session-reap] SPIKE — runner likely unhealthy",
                  buildFailurePayload(failure),
                );
                Sentry.withScope((scope) => {
                  scope.setLevel("error");
                  scope.setTags(getFailureSentryTags(failure));
                  scope.setContext("failure", buildFailurePayload(failure));
                  Sentry.captureException(failure.error);
                });
              }
            } catch (err) {
              console.error("[session-reap] failed:", err);
            }
          }

          const { autoDrainBacklog } = await import(
            "@bob/api/handlers/autoDrain"
          );
          try {
          // Optional agent allow-list (comma-separated) so an agent with broken
          // credentials can be pulled from rotation with a var change.
          const agentsVar = String(runtimeEnv.BOB_AUTO_DRAIN_AGENTS ?? "").trim();
          const agents = agentsVar
            ? agentsVar.split(",").map((a) => a.trim()).filter(Boolean)
            : undefined;
          const result = await autoDrainBacklog({ concurrency, dailyCap, agents });
          console.log(
            `[auto-drain] dispatched=${result.dispatched} running=${result.running} today=${result.dispatchedToday}` +
              (result.reason ? ` reason="${result.reason}"` : "") +
              (result.items.length
                ? ` items=${result.items.map((i) => `${i.identifier}:${i.agentType}`).join(",")}`
                : ""),
          );
        } catch (error) {
          const { buildFailurePayload, getFailureSentryTags } = await import(
            "@bob/observability/failures"
          );
          const failure = {
            surface: "job" as const,
            operation: "auto_drain_backlog",
            error,
            alertId: "auto-drain-failure",
            tenant: runtimeEnv.BOB_TENANT_ID
              ? { tenantId: String(runtimeEnv.BOB_TENANT_ID) }
              : undefined,
          };
          console.error(
            "[auto-drain] failed",
            buildFailurePayload(failure),
          );
          Sentry.withScope((scope) => {
            scope.setLevel("error");
            scope.setTags(getFailureSentryTags(failure));
            scope.setContext("failure", buildFailurePayload(failure));
            Sentry.captureException(
              error instanceof Error ? error : new Error(String(error)),
            );
          });
          throw error;
        }
        }

        // 1a'. Starvation probe: work waiting + slots free + cap headroom but no
        // execute run for >2h means the loop is broken somewhere downstream of
        // the counters (worktree, git auth, agent permission, claim path).
        if (autoDrainOn && String(runtimeEnv.BOB_STARVATION_ALERT_ENABLED ?? "true") !== "false") {
          try {
            const { checkStarvation } = await import("@bob/api/handlers/checkStarvation");
            const s = await checkStarvation({
              windowMs: Number(runtimeEnv.BOB_STARVATION_WINDOW_MS ?? 2 * 60 * 60 * 1000),
              fallbackConcurrency: concurrency,
              fallbackDailyCap: dailyCap,
            });
            if (s.starved) {
              const { buildFailurePayload, getFailureSentryTags } = await import(
                "@bob/observability/failures"
              );
              const failure = {
                surface: "job" as const,
                operation: "auto_drain_backlog",
                error: new Error(
                  `dispatch starved: ${s.dispatchable} dispatchable, ${s.activeSessions}/${s.concurrency} slots busy, ${s.executeToday}/${s.dailyCap} cap used, last execute run ${s.minutesSinceLastExecute ?? "never today"} min ago`,
                ),
                alertId: "auto-drain-starved",
                tenant: runtimeEnv.BOB_TENANT_ID
                  ? { tenantId: String(runtimeEnv.BOB_TENANT_ID) }
                  : undefined,
              };
              console.error("[auto-drain] STARVED", buildFailurePayload(failure));
              Sentry.withScope((scope) => {
                scope.setLevel("error");
                scope.setTags(getFailureSentryTags(failure));
                scope.setContext("failure", buildFailurePayload(failure));
                Sentry.captureException(failure.error);
              });
            }
          } catch (err) {
            console.error("[auto-drain] starvation probe failed:", err);
          }
        }

        // 1b. Walk active plan checklists one gated item at a time (dark by
        // default). Independent of auto-drain; safe no-op when no plan is active.
        if (advanceChecklistOn) {
          try {
            const { advanceChecklist } = await import(
              "@bob/api/handlers/advanceChecklist"
            );
            const r = await advanceChecklist({});
            if (r.actions.length) {
              console.log(
                `[advance-checklist] plans=${r.plansSeen} ` +
                  r.actions
                    .map((a) => `${a.action}${a.itemId ? `(${a.itemId})` : ""}`)
                    .join(","),
              );
            }
          } catch (error) {
            console.error("[advance-checklist] failed:", error);
          }
        }

        // 2. Review + auto-merge the PRs those tasks produced.
        if (autoMergeOn) {
          const { autoReviewAndMerge } = await import(
            "@bob/api/handlers/autoMergeReview"
          );
          const r = await autoReviewAndMerge({
            maxPerRun: Number(runtimeEnv.BOB_AUTO_MERGE_MAX_PER_RUN ?? 5),
            reviewAgentType:
              (runtimeEnv.BOB_AUTO_MERGE_REVIEW_AGENT as string | undefined) ??
              "codex",
            dryRun: String(runtimeEnv.BOB_AUTO_MERGE_DRY_RUN ?? "") === "true",
            forgejoToken: runtimeEnv.BOB_FORGEJO_TOKEN as string | undefined,
            forgejoInstanceUrl:
              (runtimeEnv.BOB_FORGEJO_INSTANCE_URL as string | undefined) ??
              "https://git.forgegraf.com",
            // Dedicated reviewer bot (separate identity — the git host rejects
            // self-reviews on the author's own PRs).
            reviewForgejoToken: runtimeEnv.BOB_REVIEW_FORGEJO_TOKEN as
              | string
              | undefined,
            reviewerLogin:
              (runtimeEnv.BOB_AUTO_MERGE_REVIEWER_LOGIN as string | undefined) ??
              "bob-reviewer",
            // Auto-repair: send a runner agent to fix PRs stuck on CI/conflict/
            // requested-changes so the review→repair→merge loop converges.
            repairEnabled:
              String(runtimeEnv.BOB_AUTO_REPAIR_ENABLED ?? "") === "true",
            repairAgentType:
              (runtimeEnv.BOB_AUTO_REPAIR_AGENT as string | undefined) ?? "codex",
            maxRepairsPerRun: Number(runtimeEnv.BOB_AUTO_REPAIR_MAX_PER_RUN ?? 3),
            maxRepairAttemptsPerPr: Number(
              runtimeEnv.BOB_AUTO_REPAIR_MAX_ATTEMPTS_PER_PR ?? 3,
            ),
          });
          console.log(
            `[auto-merge] scanned=${r.scanned} reviewed=${r.reviewed} repaired=${r.repaired} merged=${r.merged} skipped=${r.skipped}` +
              (r.authFailures ? ` authFailures=${r.authFailures}` : "") +
              (r.items.length
                ? ` items=${r.items.map((i) => `${i.pr}:${i.action}${i.reason ? `(${i.reason})` : ""}`).join(", ")}`
                : ""),
          );
          // Silent-dead-loop guard: a revoked/expired shared Forgejo token makes
          // EVERY PR 401 and get counted as an ordinary "skip", so the counters
          // look healthy (scanned=N skipped=N) while the review→repair→merge loop
          // is fully dead — exactly the 2026-07-29 outage that went unnoticed for
          // ~23h. Escalate loudly when auth failures dominate a run that produced
          // no forward progress. Threshold (not >0) so a single expired per-user
          // OAuth connection doesn't page.
          const authDominates =
            r.authFailures > 0 &&
            r.reviewed + r.repaired + r.merged === 0 &&
            r.authFailures >= Math.max(3, Math.floor(r.scanned / 2));
          if (authDominates) {
            const { buildFailurePayload, getFailureSentryTags } = await import(
              "@bob/observability/failures"
            );
            const failure = {
              surface: "job" as const,
              operation: "auto_merge_review",
              error: new Error(
                `auto-merge git-host auth failing on ${r.authFailures}/${r.scanned} PRs with 0 forward progress — shared Forgejo token likely revoked/expired`,
              ),
              alertId: "auto-merge-auth-failure",
              tenant: runtimeEnv.BOB_TENANT_ID
                ? { tenantId: String(runtimeEnv.BOB_TENANT_ID) }
                : undefined,
            };
            console.error(
              "[auto-merge] AUTH FAILURE — dispatch loop is dead",
              buildFailurePayload(failure),
            );
            Sentry.withScope((scope) => {
              scope.setLevel("error");
              scope.setTags(getFailureSentryTags(failure));
              scope.setContext("failure", buildFailurePayload(failure));
              Sentry.captureException(failure.error);
            });
          }
        }

        // 2b. Daily digest (once per UTC day at/after BOB_DIGEST_HOUR_UTC):
        // last-24h loop metrics → pinned Kanbanger issue + in-app notification.
        if (String(runtimeEnv.BOB_DAILY_DIGEST_ENABLED ?? "true") !== "false") {
          try {
            const { dailyDigest } = await import("@bob/api/handlers/dailyDigest");
            const r = await dailyDigest({
              hourUtc: Number(runtimeEnv.BOB_DIGEST_HOUR_UTC ?? 13),
              dailyCap,
            });
            if (r.posted || (r.reason && !/before digest hour|already posted/.test(r.reason))) {
              console.log(`[daily-digest] posted=${r.posted}${r.reason ? ` reason="${r.reason}"` : ""}${r.date ? ` date=${r.date}` : ""}`);
            }
          } catch (error) {
            console.error("[daily-digest] failed:", error);
          }
        }

        // 3. Deploy stage: after merges, read deploy evidence (Actions run on
        // the merge SHA / ForgeGraph deployment by commitSha) and write it back
        // to the tracker card + work item. Best-effort; never blocks the loop.
        if (deployTrackingOn) {
          try {
            const { trackDeployments } = await import(
              "@bob/api/handlers/trackDeployments"
            );
            const r = await trackDeployments({
              forgejoToken: runtimeEnv.BOB_FORGEJO_TOKEN as string | undefined,
              forgejoInstanceUrl:
                (runtimeEnv.BOB_FORGEJO_INSTANCE_URL as string | undefined) ??
                "https://git.forgegraf.com",
              fgApiToken: (runtimeEnv as any).FG_API_TOKEN as string | undefined,
              fgApiUrl: (runtimeEnv as any).FG_API_URL as string | undefined,
              maxPerRun: Number(runtimeEnv.BOB_DEPLOY_TRACKING_MAX_PER_RUN ?? 20),
            });
            if (r.scanned > 0) {
              console.log(
                `[deploy-track] scanned=${r.scanned} finalized=${r.finalized} pending=${r.pending}` +
                  (r.items.length
                    ? ` items=${r.items.map((i) => `${i.pr}:${i.outcome}${i.detail ? `(${i.detail})` : ""}`).join(", ")}`
                    : ""),
              );
            }
          } catch (error) {
            console.error("[deploy-track] failed:", error);
          }
        }
      });
      ctx.waitUntil(work);
      await work;
    },
    fetch: wrapFetch(
      async (
        request: Request,
        rawEnv: Record<string, unknown> | undefined,
        ctx,
      ): Promise<Response> => {
        const url = new URL(request.url);
        const runtimeEnv = (rawEnv ?? {}) as Env;
        applyRuntimeAuthEnv(runtimeEnv);
        applyRuntimeServiceEnv(runtimeEnv);

        // nginx uses this no-body subrequest to authorize Bob's server-to-server
        // Hermes API calls. It grants no browser session and performs no proxying.
        if (url.pathname === "/api/internal/hermes-origin-auth") {
          const authorization = request.headers.get("authorization");
          const requestedMethod = request.headers.get("x-hermes-auth-method");
          const requestedUri = request.headers.get("x-hermes-auth-uri");
          const notificationAuthorized = verifyOriginAuthorization(
            authorization,
            runtimeEnv.HERMES_ORIGIN_TOKEN ?? process.env.HERMES_ORIGIN_TOKEN ?? "",
          ) && isAllowedHermesServiceRequest(requestedMethod, requestedUri);
          const proxyAuthorized = verifyOriginAuthorization(
            authorization,
            runtimeEnv.HERMES_PROXY_ORIGIN_TOKEN ?? process.env.HERMES_PROXY_ORIGIN_TOKEN ?? "",
          ) && isAllowedHermesProxyServiceRequest(requestedMethod, requestedUri);
          const serviceAuthorized = notificationAuthorized || proxyAuthorized;
          if (serviceAuthorized) return new Response(null, { status: 204 });

          const { connectionString, isHyperdrive } =
            getHyperdriveConnectionString(runtimeEnv);
          const session = await runWithDb(
            connectionString,
            isHyperdrive,
            async () => {
              const { auth } = await import("../src/auth/server");
              return auth.api.getSession({ headers: request.headers });
            },
          );
          const operatorUserIds =
            runtimeEnv.HERMES_OPERATOR_USER_IDS ??
            process.env.HERMES_OPERATOR_USER_IDS;
          return new Response(null, {
            status:
              session?.user &&
              isAuthorizedHermesOperator(session.user.id, operatorUserIds)
                ? 204
                : 401,
          });
        }

        const isHermesDashboard = isHermesProxyPath(url.pathname);
        const isHermesNativeApi = isHermesNativeApiPath(url.pathname);
        if (isHermesDashboard || isHermesNativeApi) {
          const { connectionString, isHyperdrive } =
            getHyperdriveConnectionString(runtimeEnv);
          const session = await runWithDb(
            connectionString,
            isHyperdrive,
            async () => {
              const { auth } = await import("../src/auth/server");
              return auth.api.getSession({ headers: request.headers });
            },
          );
          if (!session?.user) {
            const loginUrl = getHermesLoginRedirect(request);
            return loginUrl
              ? Response.redirect(loginUrl, 302)
              : Response.json({ error: "unauthorized" }, { status: 401 });
          }

          const operatorUserIds =
            runtimeEnv.HERMES_OPERATOR_USER_IDS ??
            process.env.HERMES_OPERATOR_USER_IDS;
          if (!isAuthorizedHermesOperator(session.user.id, operatorUserIds)) {
            return Response.json({ error: "forbidden" }, { status: 403 });
          }
          const browserValidation = validateHermesBrowserRequest(request);
          if (browserValidation) {
            return Response.json(
              { error: browserValidation.error },
              { status: browserValidation.status },
            );
          }

          const proxyToken =
            runtimeEnv.HERMES_PROXY_ORIGIN_TOKEN ??
            process.env.HERMES_PROXY_ORIGIN_TOKEN;
          if (!proxyToken) {
            return Response.json(
              { error: "hermes_proxy_unavailable" },
              { status: 503 },
            );
          }
          const hermesOrigin =
            runtimeEnv.HERMES_ORIGIN_URL ??
            process.env.HERMES_ORIGIN_URL ??
            "https://claude.gmac.io";

          try {
            if (isHermesDashboard) {
              const upstream = await fetch(
                createHermesProxyRequest(request, hermesOrigin, proxyToken),
              );
              if (
                request.headers.get("upgrade")?.toLowerCase() === "websocket"
              ) {
                return upstream;
              }
              return sanitizeHermesResponse(
                upstream,
                url.origin,
                hermesOrigin,
              );
            }

            const validationError =
              await validateHermesNativeApiMutation(request);
            if (validationError) {
              return Response.json(
                {
                  detail: validationError.message,
                  field: validationError.field,
                },
                { status: 400 },
              );
            }
            const bootstrap = await fetch(
              createHermesBootstrapRequest(request, hermesOrigin, proxyToken),
            );
            if (!bootstrap.ok) {
              return Response.json(
                { detail: "Hermes token bootstrap unavailable" },
                { status: 502 },
              );
            }
            const sessionToken = extractHermesSessionToken(
              await bootstrap.text(),
            );
            if (!sessionToken) {
              return Response.json(
                { detail: "Hermes session token unavailable" },
                { status: 502 },
              );
            }

            if (
              url.pathname === "/api/hermes/overview" &&
              request.method === "GET"
            ) {
              const overview = await fetchHermesOverview({
                origin: hermesOrigin,
                proxyToken,
                sessionToken,
              });
              return Response.json(overview);
            }
            const upstream = await fetch(
              createHermesNativeApiRequest(
                request,
                hermesOrigin,
                proxyToken,
                sessionToken,
              ),
            );
            return sanitizeHermesResponse(
              upstream,
              url.origin,
              hermesOrigin,
            );
          } catch (error) {
            console.error(
              "[hermes-proxy] upstream request failed",
              error instanceof Error ? error.message : "unknown error",
            );
            return Response.json(
              { detail: "Hermes proxy unavailable" },
              { status: 502 },
            );
          }
        }

        // WebSocket proxy to gateway — forward upgrade to origin
        if (
          url.pathname === "/ws/sessions" &&
          request.headers.get("Upgrade") === "websocket"
        ) {
          const gatewayOrigin =
            runtimeEnv.GATEWAY_URL ||
            process.env.GATEWAY_URL ||
            "https://ws.blder.bot";
          const target = `${gatewayOrigin}/sessions${url.search}`;
          return fetch(target, request);
        }

        // Image optimization via Cloudflare Images binding.
        if (url.pathname === "/_vinext/image") {
          if (!runtimeEnv.ASSETS || !runtimeEnv.IMAGES) {
            return new Response(
              "Image optimization is unavailable in this runtime",
              { status: 503 },
            );
          }
          const allowedWidths = [
            ...DEFAULT_DEVICE_SIZES,
            ...DEFAULT_IMAGE_SIZES,
          ];
          return handleImageOptimization(
            request,
            {
              fetchAsset: (path) =>
                runtimeEnv.ASSETS.fetch(
                  new Request(new URL(path, request.url)),
                ),
              transformImage: async (body, { width, format, quality }) => {
                const result = await runtimeEnv.IMAGES.input(body)
                  .transform(width > 0 ? { width } : {})
                  .output({ format, quality });
                return result.response();
              },
            },
            allowedWidths,
          );
        }

        // Expose secrets to server-side code via globalThis.
        const nudgeSecret =
          runtimeEnv.NUDGE_SHARED_SECRET ?? process.env.NUDGE_SHARED_SECRET;
        if (nudgeSecret) {
          (globalThis as any).NUDGE_SHARED_SECRET = nudgeSecret;
        }

        // Run vinext with a request-scoped DB client.
        const { connectionString, isHyperdrive } =
          getHyperdriveConnectionString(runtimeEnv);
        return runWithDb(connectionString, isHyperdrive, () =>
          handler.fetch(request, runtimeEnv, ctx),
        );
      },
    ),
  },
);
