import createClient from "openapi-fetch";
import type { paths } from "./schema.js";
import { makeAgentClient, type AgentClient } from "./agent.js";
import { makeAuthClient, type AuthClient } from "./auth.js";
import { makeExternalClient, type ExternalClient } from "./external.js";
import { makePlanningClient, type PlanningClient } from "./planning.js";
import { makeProjectsClient, type ProjectsClient } from "./projects.js";
import { makeSecretsClient, type SecretsClient } from "./secrets.js";
import { makeSettingsClient, type SettingsClient } from "./settings.js";
import { makeWorkItemsClient, type WorkItemsClient } from "./work-items.js";
import {
  makeRuntime,
  type ClientRuntimeOptions,
} from "./internal/runtime.js";

export type BobClientOptions = ClientRuntimeOptions;

export interface BobRpcClient {
  readonly workItems: WorkItemsClient;
  readonly planning: PlanningClient;
  readonly external: ExternalClient;
  readonly agent: AgentClient;
  readonly projects: ProjectsClient;
  readonly settings: SettingsClient;
  readonly secrets: SecretsClient;
  readonly auth: AuthClient;
}

export const createBobRpcClient = (opts: BobClientOptions): BobRpcClient => {
  const runtime = makeRuntime(opts);
  return {
    workItems: makeWorkItemsClient(runtime),
    planning: makePlanningClient(runtime),
    external: makeExternalClient(runtime),
    agent: makeAgentClient(runtime),
    projects: makeProjectsClient(runtime),
    settings: makeSettingsClient(runtime),
    secrets: makeSecretsClient(runtime),
    auth: makeAuthClient(runtime),
  };
};

/**
 * Typed REST/HTTP client for Bob's OpenAPI surface.
 *
 * The `paths` type is generated by `openapi-typescript` from
 * `packages/bob-client/openapi/bob.json`, which is itself generated from Bob's
 * Effect-RPC contract groups (`pnpm generate:openapi:bob`). Every operation is
 * `POST /api/v1/{tag}` and is fully request/response typed.
 *
 * Use {@link createBobRpcClient} for in-app calls over the Effect-RPC transport
 * (`/api/rpc`); use this for plain typed HTTP — external consumers, codegen, or
 * environments without the Effect runtime.
 */
export function createBobClient(baseUrl = "https://bob.blder.bot") {
  return createClient<paths>({ baseUrl });
}

export type { paths };

export const __bobClientPhase = "effect-rpc-client" as const;
